apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: index.docker.io/sourcegraph/alpine-3.14:insiders@sha256:c9b3c12e4fb26545c2122d8a0791b475148f937d28e778613916087a0d5a3ae9
          command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana"]
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
          securityContext:
            runAsUser: 0
