apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: index.docker.io/sourcegraph/alpine-3.14:6.4.0@sha256:5a7034f0a4e19b4c46e8ac529df36f79c2d64330f239ed5f41bb3a19c3d70875
          command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana"]
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
          securityContext:
            runAsUser: 0
