apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Backend for indexed text search operations.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: indexed-search
  name: indexed-search
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexed-search
  serviceName: indexed-search
  template:
    metadata:
      labels:
        app: indexed-search
        deploy: sourcegraph
    spec:
      containers:
      - name: zoekt-webserver
        env:
        # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
        - name: OTEL_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_AGENT_HOST):4317
        - name: OPENTELEMETRY_DISABLED
          value: "false"
        image: index.docker.io/sourcegraph/indexed-searcher:6.4.0@sha256:c301e0c9f485ecefcaca994a96e8f063e9635206b22bc90206590d1685e08026
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 6070
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 4G
          requests:
            cpu: 500m
            memory: 2G
        volumeMounts:
        - mountPath: /data
          name: data
      - name: zoekt-indexserver
        env:
        # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
        - name: OTEL_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_AGENT_HOST):4317
        - name: OPENTELEMETRY_DISABLED
          value: "false"
        image: index.docker.io/sourcegraph/search-indexer:6.4.0@sha256:5ff00db1e90a3f607c8e45ea404ae74bbb7d84497d3c8e0304dcb762ea29cc3f
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 6072
          name: index-http
        resources:
          # zoekt-indexserver is CPU bound. The more CPU you allocate to it, the
          # lower lag between a new commit and it being indexed for search.
          limits:
            cpu: "8"
            memory: 8G
          requests:
            cpu: "4"
            memory: 4G
        volumeMounts:
        - mountPath: /data
          name: data
      securityContext:
        runAsUser: 0
      volumes:
      - name: data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        deploy: sourcegraph
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # The size of disk to used for search indexes.
          # This should typically be gitserver disk size multipled by the number of gitserver shards.
          storage: 200Gi
      storageClassName: sourcegraph
