#!/usr/bin/env bash

set -euxo pipefail
cd $BUILDKITE_BUILD_CHECKOUT_PATH

TOOL_VERSION_FILES=$(fd .tool-versions --hidden --absolute-path)

for file in "${TOOL_VERSION_FILES[@]}"
do
    echo "Installing asdf dependencies as defined in '${file}':"
    parent=$(dirname "${file}")
    cd "${parent}"
    
    asdf install
done
