#!/usr/bin/env bash

set -eu
cd $(dirname "${BASH_SOURCE[0]}")/../..

TOOL_VERSION_FILES=()
mapfile -d $'\0' TOOL_VERSION_FILES < <(fd .tool-versions --hidden --absolute-path --print0)

for file in "${TOOL_VERSION_FILES[@]}"
do
    echo "Installing asdf dependencies as defined in ${file}:"
    parent=$(dirname "${file}")
    cd "${parent}"
    
    asdf install
done
